model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: True
  prompt_template: '[INST] {} [/INST]'
  ckpt: /data/kpahwa/random/MiniGPT-4/save_ckpt/20240414220/checkpoint_49.pth
  lora_r: 64
  lora_alpha: 16


datasets:
  pmc_vqa:    
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    

  pmc_caption:
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 50

run:
  task: image_text_pretrain
